### ISSUE TITLE
Easing stopped working since 3.2.2 update

### ISSUE THREAD

**Issue by artemverbo** [pavel-mazhuga/lit-scroll#2]
Hi @pavel-mazhuga! Thanks for a great lightweight custom scrolling lib.

Just wondering, since updating to 3.2.2, I've lost the "inertia/smoothness" of the scroll, no matter what `ease` value is set. When downgrading to 3.2.1 it works again. Has something changed in terms of how it supposed to be used maybe?

**Comment by pavel-mazhuga** [comment]
Hi @artemverbo! Thank you :) My apologies for breaking the 3.2.2 version, fixed the issue in 3.2.3.
